# Generated by Django 5.1.2 on 2024-12-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gotti', '0004_carrito_cancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
    ]
